version: '3'
services:
  web:
    build: .
    image: apitest
    ports:
      - "8080:3000"
    command: npm start
    volumes:
      - .:/usr/src
      - node_modules:/usr/src/node_modules
volumes:
  node_modules: